# Generated by Django 4.2.7 on 2023-11-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("sno", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=13)),
                ("content", models.TextField()),
            ],
        ),
    ]
